AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Employee_POC

  Sample SAM Template for Employee_POC

Globals:
  Function:
    Runtime: python3.9
    Architectures:
      - x86_64
    Timeout: 40

Resources:
  GetAllEmployeeDetails:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Employee/
      Handler: get_all_employee.lambda_handler

  CreateEmployeeDetails:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Employee/
      Handler: create_emp_details.lambda_handler

  GetEmployeeDetailsById:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Employee/
      Handler: get_emp_by_id.lambda_handler

  DeleteEmployeeDetailsById:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Employee/
      Handler: delete_emp_by_id.lambda_handler